apiVersion: apps/v1       
kind: Deployment          
metadata:
  name: catalog            
  labels:
    app: catalog          
spec:
  replicas: 1            
  selector:
    matchLabels:
      app: catalog         
  template:
    metadata:
      labels:
        app: catalog       
    spec:
      containers:
        - name: catalog
          image: public.ecr.aws/aws-containers/retail-store-sample-catalog:1.6.1
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: RETAIL_CATALOG_PERSISTENCE_PROVIDER
              value: "mysql"
            - name: RETAIL_CATALOG_PERSISTENCE_ENDPOINT
              value: "catalog-db:3306"
            - name: RETAIL_CATALOG_PERSISTENCE_DB_NAME
              value: "catalogdb"
            - name: RETAIL_CATALOG_PERSISTENCE_USER
              value: "catalog_user"
            - name: RETAIL_CATALOG_PERSISTENCE_PASSWORD
              value: "password123"
          resources:
            requests:
              cpu: "128m"
              memory: "128Mi"
            limits:
              cpu: "256m"
              memory: "256Mi"