apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      containers:
      - name: checkout
        image: public.ecr.aws/aws-containers/retail-store-sample-checkout:1.6.1

        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env: 
        - name: PORT
          value: "8080"
        - name : RETAIL_CHECKOUT_PERSISTENCE_PROVIDER
          value: redis
        - name: RETAIL_CHECKOUT_PERSISTENCE_REDIS_URL
          value: "REPLACE_WITH_ELASTICACHE_ENDPOINT"
        - name: RETAIL_CHECKOUT_ENDPOINTS_ORDERS
          value: "http://orders:8080"
