apiVersion: v1
kind: Service
metadata:
  name: catalog
spec:
  selector:
    app: catalog         # finds pods with this label
  ports:
    - port: 8080         # service port
      targetPort: 8080   # pod port
  type: ClusterIP        # only accessible inside cluster